require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5.0
  NewCops: disable
  SuggestExtensions: false

Gemspec/OrderedDependencies:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Lint/DeprecatedConstants:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

Metrics/MethodLength:
  Exclude:
    - test/**/*.rb
  Max: 15

Metrics/AbcSize:
  Exclude:
    - test/**/*.rb

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 2

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/MultilineBlockChain:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  MinSize: 5

Style/TrailingUnderscoreVariable:
  AllowNamedUnderscoreVariables: true

Style/WordArray:
  MinSize: 5

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/NegatedIfElseCondition:
  Enabled: true

Style/SwapValues:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/HashExcept:
  Enabled: true

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/Sum:
  Enabled: true

Performance/BlockGivenWithExplicitBlock:
  Enabled: true

Performance/CollectionLiteralInLoop:
  Enabled: true

Performance/ConstantRegexp:
  Enabled: true

Performance/MethodObjectAsBlock:
  Enabled: true
